// 프로젝트 루트에 최소 runtime-profile.yml 을 심는다.
// 티어는 overlay: none. 백엔드·명령은 넣지 않는다 — 프로젝트가 채운다.
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { ALIASES, ENGINES } from './engines.mjs';
import { formatValidateReport, parseProfile } from './profile.mjs';

export const PROFILE_RELPATH = path.join('.agents', 'runtime-profile.yml');

const SLUG = /^[a-z][a-z0-9_-]*$/;
const DNS_LABEL = /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/;

export function slugFromName(name) {
  let s = String(name)
    .toLowerCase()
    .replaceAll(/[^a-z0-9_-]+/g, '-')
    .replaceAll(/^-+|-+$/g, '');
  s = s.replace(/^[^a-z]+/, '');
  return s.length > 0 && SLUG.test(s) ? s : null;
}

export function parseCsv(value) {
  if (value == null || value === '') return [];
  return String(value)
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
}

export function resolveEnginesFlag(names) {
  const out = [];
  for (const name of names) {
    const canon = ALIASES[name] ?? name;
    if (!(canon in ENGINES)) {
      throw new Error(`모르는 엔진 "${name}" — 지원: ${Object.keys(ENGINES).join(', ')}`);
    }
    if (!out.includes(canon)) out.push(canon);
  }
  return out;
}

export function resolveServicesFlag(names) {
  for (const name of names) {
    if (!DNS_LABEL.test(name)) {
      throw new Error(`services 키는 DNS 라벨 — ${JSON.stringify(name)}`);
    }
  }
  return names;
}

export function parseInitArgs(args) {
  let root;
  const opts = { slug: null, engines: [], services: [], force: false };
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg === '--force') {
      opts.force = true;
      continue;
    }
    if (arg === '--slug' || arg === '--engines' || arg === '--services') {
      const value = args[i + 1];
      if (value == null || value.startsWith('--')) {
        throw new Error(`${arg} 값이 없다.`);
      }
      i += 1;
      if (arg === '--slug') opts.slug = value;
      if (arg === '--engines') opts.engines = parseCsv(value);
      if (arg === '--services') opts.services = parseCsv(value);
      continue;
    }
    if (arg.startsWith('--')) {
      throw new Error(`모르는 옵션 "${arg}"`);
    }
    if (root != null) {
      throw new Error(`프로젝트 루트는 하나 — ${JSON.stringify(arg)}`);
    }
    root = arg;
  }
  return { root: root ?? '.', ...opts };
}

export function renderInitYaml({ slug, engines = [], services = [] }) {
  if (!SLUG.test(slug)) {
    throw new Error(`project.slug 가 없거나 형식이 아니다 — ${JSON.stringify(slug)}`);
  }
  const canonEngines = resolveEnginesFlag(engines);
  const canonServices = resolveServicesFlag(services);
  const lines = [
    '# generated by de-novo-skills init — 값을 이 프로젝트에 맞게 고친다.',
    'version: 1',
    '',
    'project:',
    `  slug: ${slug}`,
    '',
    'addressing:',
    '  tld: localhost',
    '  scheme:',
    '    shared: "{service}.{project}.{tld}"',
    '',
    'runtime:',
    '  single_stack: true',
    '  writers: 1',
    '',
  ];
  if (canonServices.length > 0) {
    lines.push('services:');
    for (const name of canonServices) {
      lines.push(`  ${name}: {}`);
    }
    lines.push('');
  }
  lines.push('overlay: none', '', 'data:', '  infra: machine');
  if (canonEngines.length === 0) {
    lines.push('  engines: {}');
  } else {
    lines.push('  engines:');
    for (const name of canonEngines) {
      lines.push(`    ${name}: true`);
    }
  }
  lines.push('  forbid_direct_db_writes: true', '');
  return lines.join('\n');
}

export function runInit(args, cwd = process.cwd()) {
  const opts = parseInitArgs(args);
  const root = path.resolve(cwd, opts.root);
  const slug = opts.slug ?? slugFromName(path.basename(root));
  if (!slug) {
    throw new Error(
      `디렉터리 이름에서 slug 를 못 만든다 (${path.basename(root)}). --slug 로 지정한다.`
    );
  }
  const yamlText = renderInitYaml({
    slug,
    engines: opts.engines,
    services: opts.services,
  });
  const file = path.join(root, PROFILE_RELPATH);
  if (existsSync(file) && !opts.force) {
    throw new Error(`이미 있다: ${file}\n덮으려면 --force.`);
  }
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, yamlText);
  const profile = parseProfile(yamlText, file);
  const engineCount = Object.keys(profile.engines).length;
  const serviceCount = Object.keys(profile.services).length;
  console.log(`■ ${slug} — 프로파일 생성`);
  console.log(`  파일    1/1: ${file}`);
  console.log(`  앱      ${serviceCount} (services)`);
  console.log(`  엔진    ${engineCount} (data.engines)`);
  console.log(formatValidateReport(profile));
  console.log('다음: services·engines 값을 이 프로젝트에 맞게 고치고 de-novo-skills setup.');
  return 0;
}
